"""
Question:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Link:
https://projecteuler.net/problem=2
"""


def evenDigit(n):
    if n % 2 == 0:
        return True
    return False


sum = 2
first = 1
second = 2

while True:
    next = first + second
    if next > 4000000:
        break
    if evenDigit(next):
        sum += next
    first, second = second, next

print(sum)
